name: Stencil Utils Library
on:
    push:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            # this is crucial for bodl-events package to be able to resolve @bigcommerce-labs scoped packages
            - name: Set npm registry
              run: echo "@bigcommerce-labs:registry=https://npm.pkg.github.com/" >> ~/.npmrc
            - name: Set npm secrets
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.DEPENDABOT_GITHUB_TOKEN }}" >> ~/.npmrc
            - run: npm i
            - name: Check Git Commit name
              run: git log -1 --pretty=format:"%s" |  npx commitlint
            - run: npm run build
            - name: Deploy to npm and git
              run: npm config list && npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GA_USERNAME: ${{ secrets.PAT_USERNAME }}
                  GA_TOKEN: ${{ secrets.CUSTOM_GA_TOKEN }}

